# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Newsflash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Newsflash

  target 'NewsflashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsflashUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  
  pod 'SwiftyJSON'
  

end
